- name: Get ResourceQuota in the namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ResourceQuota
    namespace: "{{ namespace }}"
  register: quota_info

- name: Extract quota CPU and Memory
  set_fact:
    quota_cpu: "{{ quota_info.resources[0].status.hard['limits.cpu'] | default('0') }}"
    quota_memory: "{{ quota_info.resources[0].status.hard['limits.memory'] | default('0') }}"
  when: quota_info.resources | length > 0

- name: Convert quota memory to Mi
  set_fact:
    quota_memory_mi: >-
      {% if 'Gi' in quota_memory %}
        {{ (quota_memory[:-2] | float) * 1024 }}
      {% elif 'Mi' in quota_memory %}
        {{ quota_memory[:-2] | float }}
      {% else %}
        {{ quota_memory | float }}
      {% endif %}

- name: Check resource feasibility
  fail:
    msg: >-
      Resource request exceeds quota.
      Requested: {{ cpu_count }} CPUs, {{ memory }}Gi memory.
      Quota allows: {{ quota_cpu }} CPUs, {{ quota_memory }} memory.
  when: >
    (cpu_count | float) > (quota_cpu | float)
    or
    (memory | float) * 1024 > quota_memory_mi
