---
- name: Get data from user form
  hosts: localhost
  tasks:
    - name: Capture all the form data
      set_stats:
        data:
          business_group: "{{ business_group }}"
          network: "{{ network }}"
          location: "{{ location }}"
          language: "{{ language }}"
          vm_count: "{{ vm_count }}"
          size: "{{ size }}"

    - debug:
        msg: "{{ size }}"

    - name: Extract CPU count
      set_fact:
        cpu_count: "{{ size | regex_search('\\((\\d+)\\s*vCPU', '\\1') | int }}"

    - name: Extract memory
      set_fact:
        memory: "{{ size | regex_search(', (\\d+) GB RAM', '\\1') | int }}"

    - name: Save CPU and memory to stats
      set_stats:
        data:
          cpu_count: "{{ cpu_count }}"
          memory: "{{ memory }}"

    - name: Display extracted values
      debug:
        msg: "CPU Count: {{ cpu_count }}, Memory: {{ memory }} GB"
