---
- name: Get data from user form
  hosts: localhost
  tasks:
    - name: Capture all the form data
      set_stats:
        data:
          business_group: "{{ business_group }}"
          network: "{{ network }}"
          location: "{{ location }}"
          language: "{{ language }}"
          vm_count: "{{ vm_count }}"
          size: "{{ size }}"
          image_name: "{{ image }}"
          os_family: "{{ os_family }}"

    - name: Get the url
      uri:
        url: "https://raw.githubusercontent.com/Suknaina/redhat_siemens/refs/heads/main/image_path.txt"
        return_content: yes
      register: file_content

    - name: Save CPU, memory and template to stats
      set_stats:
        data:
          cpu_count: "{{ size.split('(')[1].split('vCPU')[0] | trim | int }}"
          memory: "{{ size.split(',')[1].split('GB')[0] | trim | int }}"
          template: "{{ (file_content.content.split('\n') | select('search', image) | list | first).lstrip('- ') }}"


