---
- name: Get data from user form
  hosts: localhost
  tasks:
    - name: Capture all the form data
      set_stats:
        data:
          business_group: "{{ business_group }}"
          network: "{{ network }}"
          location: "{{ location }}"
          language: "{{ language }}"
          vm_count: "{{ vm_count }}"
          size: "{{ size }}"

    - name: Show the size value
      debug: 
        msg: "The selected size is: {{ size }}"
