---
- name: Get data from user form
  hosts: localhost
  tasks:
    - name: Capture all the form data
      set_stats:
        business_group: "{{ business_group }}"
        network: "{{ network }}"
        location: "{{ location }}"
        language: "{{ language }}"
        vm_count: "{{ vm_count }}"
        size: "{{ size }}"

    - debug: 
        msg: "{{ size }}"
