---
# tasks file for vm_hostname
- name: Run Python script to generate hostname
  script: "generate_hostname.py {{ location }} {{ os_family }}"
  register: hostname_output

- name: Set hostname fact
  set_fact:
    hostname: "{{ hostname_output.stdout }}"

- name: Show generated hostname
  debug:
    msg: "Generated hostname is {{ hostname }}"

