- name: Ensure Git safe.directory is trusted
  ansible.builtin.command:
    cmd: git config --global --add safe.directory "{{ repo_path }}"
  become: true
  become_user: awx
  changed_when: false  # Idempotency

- name: Perform git pull in the repo
  ansible.builtin.command:
    cmd: git pull
    chdir: "{{ repo_path }}"
  become: true
  become_user: awx
  register: git_pull_result
  failed_when: git_pull_result.rc != 0
  ignore_errors: false

- name: Add all changes
  command: git add .
  args:
    chdir: "{{ repo_path }}"
  become: true
  become_user: awx
  register: git_add_result
  failed_when: git_add_result.rc != 0

- name: Commit changes
  command: git commit -m "{{ commit_message }}"
  args:
    chdir: "{{ repo_path }}"
  become: true
  become_user: awx
  register: git_commit_result
  when: git_commit_result.rc == 0

- name: Push changes to remote
  command: git push "https://{{ git_username }}:{{ git_password }}@{{ github_repo_url }}"
  args:
    chdir: "{{ repo_path }}"
  become: true
  become_user: awx
  register: git_push_result
  when: git_push_result.rc == 0 and git_commit_result.rc == 0
