- name: Ensure Git safe.directory is trusted
  ansible.builtin.command:
    cmd: git config --global --add safe.directory "{{ repo_path }}"
  become: true
  become_user: awx
  changed_when: false  # Idempotency

- name: Perform git pull in the repo
  ansible.builtin.command:
    cmd: git pull
    chdir: "{{ repo_path }}"
  become: true
  become_user: awx
  register: git_pull_result
  failed_when: git_pull_result.rc != 0
  ignore_errors: false

- name: Print git pull result
  ansible.builtin.debug:
    var: git_pull_result.stdout_lines
