- name: Read existing attribute values from YAML file with sudo
  ansible.builtin.slurp:
    path: "/var/lib/awx/projects/sukanya/siemens/redhat_siemens/meta_files/{{ attribute_name | lower | replace(' ', '_') }}.yml"
  register: attribute_file_content
  failed_when: attribute_file_content is failed
  become: yes

- name: Decode and parse YAML content
  set_fact:
    existing_values: "{{ attribute_file_content.content | b64decode | from_yaml }}"

- name: Fail if values_string_normalized exists in existing_values
  fail:
    msg: "Value '{{ values_string_normalized }}' already exists in {{ attribute_name }} file!"
  when: values_string_normalized in existing_values

- name: Append new value to YAML file
  lineinfile:
    path: "/var/lib/awx/projects/sukanya/siemens/redhat_siemens/meta_files/{{ attribute_name | lower | replace(' ', '_') }}.yml"
    line: "- {{ values_string_normalized }}"
    insertafter: EOF
    mode: '0644'
  when: values_string_normalized not in existing_values
  become: yes

- name: Debug message when value added successfully
  debug:
    msg: "Value '{{ values_string_normalized }}' added successfully to {{ attribute_name }} file."
  when: values_string_normalized not in existing_values
