- name: Ensure CSV file exists with correct header
  lineinfile:
    path: "/tmp/user_values.csv"
    line: "Business Group,Location,Size,User name,User mail"
    create: yes
    insertafter: BOF

- name: Include tasks for user details
  include_role:
    name: vm_proision
    tasks_from: user_details.yml

- name: Initialize row_values dict with empty values
  set_fact:
    row_values:
      Business Group: ""
      Location: ""
      Network: ""
      User name: "{{ launched_by }}"
      User mail: "{{ user_email }}"

- name: Populate attribute values in the row
  set_fact:
    row_values: >-
      {{
        row_values.update({ attribute_name: values_list | join(';') }) or row_values
      }}

- name: Format new CSV line string
  set_fact:
    new_csv_line: "{{ row_values['Business Group'] }},{{ row_values['Location'] }},{{ row_values['Network'] }},{{ row_values['User name'] }},{{ row_values['User mail'] }}"

- name: Append new CSV line to file
  lineinfile:
    path: "{{ /tmp/user_values.csv }}"
    line: "{{ new_csv_line }}"

