---
- name: Read file
  ansible.builtin.slurp:
    src: image_path.template
  register: url_content

- name: Decode file and convert to list
  set_fact:
    url_list: "{{ url_content['content'] | b64decode | from_yaml }}"

- name: Extract image names and store in list
  set_fact:
    image_names: "{{ image_names + [item.split('/')[-1].split('.')[0]] }}"
  loop: "{{ url_list }}"

- name: Write image names to file
  delegate_to: 172.16.3.42
  become: yes
  lineinfile:
    line: "{{ image_names | to_nice_yaml }}"
    path: "/var/lib/awx/projects/sukanya/siemens/redhat_siemens/meta_files/image_urls.yml"
    insertafter: EOF
    mode: '0644'
    create: yes

- name: Include role to update git
  include_role: 
    name: git_update
