---
- name: Fetch url template list from url
  uri:
    url: "https://raw.githubusercontent.com/Suknaina/redhat_siemens/refs/heads/main/image_path.txt"
    return_content: yes
  register: url_lists
  
- name: Get the content list
  set_fact:
    url_list: "{{ url_lists.content | from_yaml }}"

- name: Extract image names and store in list
  set_fact:
    image_names: "{{ image_names + [item.split('/')[-1].rsplit('.', 1)[0]] }}"
  loop: "{{ url_list }}"

- name: Clear file before use
  become: yes
  copy:
    content: ""
    dest: "/var/lib/awx/projects/sukanya/siemens/redhat_siemens/meta_files/image_urls.yml"
    
- name: Write image names to file
  become: yes
  lineinfile:
    line: "{{ image_names | to_nice_yaml }}"
    path: "/var/lib/awx/projects/sukanya/siemens/redhat_siemens/meta_files/image_urls.yml"
    insertafter: EOF
    mode: '0644'
    group: awx
    owner: awx
    create: yes

- name: Include role to update git
  include_role: 
    name: git_update
