---
# tasks file for update_survey
- name: Load choices using slurp instead of file lookup
  become: yes
  ansible.builtin.slurp:
    path: "{{ meta_file_base_path }}/{{ item.file }}"
  register: slurped_files
  loop: "{{ survey_question_list }}"

- name: Decode and parse slurped YAML content
  set_fact:
    survey_spec: "{{ survey_spec | default([]) + [ {
      'question_name': item.item.name,
      'variable': item.item.var,
      'type': 'multiplechoice',
      'required': true,
      'choices': (item.content | b64decode | from_yaml)
    } ] }}"
  loop: "{{ slurped_files.results }}"


- name: Update the survey for job template
  uri:
    url: "{{ aap_url }}/api/controller/v2/job_templates/{{ job_template_id }}/survey_spec/"
    method: POST
    user: "{{ aap_username }}"
    password: "{{ aap_password }}"
    force_basic_auth: true
    validate_certs: false
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Dynamic Survey"
      description: "Survey generated from multiple YAML files"
      spec: "{{ survey_spec }}"
    status_code: 200

