- name: Add vm_count and size questions to survey_spec
  set_fact:
    survey_spec: "{{ survey_spec + extra_questions }}"
  vars:
    survey_spec: "{{ survey_spec | default([]) + [ {
      'question_name': item.name,
      'variable': item.var,
      'type': 'multiplechoice',
      'required': true,
      'choices': (lookup('file', item.file) | from_yaml),
      'default': ''
    } ] }}"
    extra_questions:
     - question_name: "Number of VMs"
       variable: "vm_count"
       type: "integer"
       required: true
       default: 1
       min: 1
       max: 10
     - question_name: "OS Family"
       variable: "os_family"
       type: "multiplechoice"
       required: true
       choices:
         - Windows
         - Linux
       default: ""
     - question_name: "Select VM Size"
       variable: "size"
       type: "multiplechoice"
       required: true
       choices:
         - S (4 vCPU, 8 GB RAM)
         - M (8 vCPU, 16 GB RAM)
         - L (16 vCPU, 32 GB RAM)
       default: M (8 vCPU, 16 GB RAM)
