---
- name: Create VirtualMachine from existing DataVolume
  k8s:
    state: present
    definition:
      apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      metadata:
        name: vm-from-rhel-9-2
        namespace: default
      spec:
        running: false
        template:
          metadata:
            labels:
              kubevirt.io/domain: vm-from-rhel-9-2
          spec:
            domain:
              devices:
                disks:
                  - name: rootdisk
                    disk:
                      bus: virtio
              resources:
                requests:
                  memory: 2Gi
                  cpu: "2"
            volumes:
              - name: rootdisk
                dataVolume:
                  name: rhel-9-2
