---
# tasks file for vm_provision
- name: include cred file
  include_vars: admin_creds.yml
  
- name: Include tasks to create VM from datavolume
  include_tasks: datavolume.yml
  when: creation_type == 'datavolume'

- name: Include tasks to create VM from template
  include_tasks: template.yml
  when: creation_type == 'template'

- name: Include tasks to create VM from url
  include_tasks: url_method.yml
  when: creation_type == 'url'

- name: Include tasks to get launched users details
  include_tasks: user_details.yml



