---
# tasks file for vm_provision
- name: Include tasks to create VM from datavolume
  include_tasks: datavolume.yml
  when: creation_type == 'datavolume'

- name: Include tasks to create VM from template
  include_tasks: template.yml
  when: creation_type == 'template'

- name: Show who launched the job
  include_tasks: job_launched_username.yml


