---
# tasks file for vm_provision
- name: Get ResourceQuota in the namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ResourceQuota
    namespace: aap-poc
  register: quota_info
      
- name: include cred file
  include_vars: admin_creds.yml
  
- name: Include tasks to create VM from datavolume
  include_tasks: datavolume.yml
  when: creation_type == 'datavolume'

- name: Include tasks to create VM from template
  include_tasks: template.yml
  when: creation_type == 'template'

- name: Create VM using url
  block:
    - name: include vars for url method
      include_vars: url_vars.yml
      
    - name: Include tasks to create VM from url
      include_tasks: url_method.yml
      when: os_family == 'Linux'
      
  when: creation_type == 'url'

- name: Include tasks to get launched users details
  include_tasks: user_details.yml



