---
# tasks file for vm_provision
- name: Include tasks to create VM from datavolume
  include_tasks: datavolume.yml
  when: creation_type == 'datavolume'

- name: Include tasks to create VM from template
  include_tasks: template.yml
  when: creation_type == 'template'

- name: Username who launched the template
  debug: 
    msg: launched_by: "{{ tower_user.username }}"

