- debug:
    msg: "{{ launched_by }}"
    
- name: Get user details from AAP API
  uri:
    url: "https://aap-platform-aap.apps.ocp4.imss.work/api/controller/v2/users/?username={{ launched_by }}"
    method: GET
    user: "{{ username }}"
    password: "{{ password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  register: user_info

- name: Set email fact
  debug:
    msg: "user_email: {{ user_info.json.results[0].email }} and User UUID is {{ (user_info.json.summary_fields.resource.ansible_id) }}"

